language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "node"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
install:
  - npm install
